import {
    StatusRule,
    StatusPermissions,
    GeofenceConfig,
    StatusValidations,
    UIContentConfig,
} from '../lib/remoteConfig/types';

const DEFAULT_STATUS_RULES: Record<number, StatusRule> = {
    10: {
        status_id: 10,
        name: 'DELIVERED',
        call_required: false,
        photo_required: false,
        reason_required: false,
        two_step: false,
        customer_confirmation: true,
        max_photos: 5,
        photo_description: 'Take photos of delivered items',
    },
    16: {
        status_id: 16,
        name: 'CORRECT CONTACT DETAILS REQUIRED',
        call_required: false,
        photo_required: true,
        reason_required: false,
        two_step: false,
        customer_confirmation: false,
        max_photos: 2,
        photo_description: 'Take a photo of the parcel',
    },
    17: {
        status_id: 17,
        name: 'LEFT MESSAGE NOTE AT DOOR',
        call_required: true,
        photo_required: true,
        reason_required: false,
        two_step: false,
        customer_confirmation: false,
        max_photos: 2,
        photo_description: 'Take a photo of the location where you left the message note',
    },
    22: {
        status_id: 22,
        name: 'ON HOLD FOR PICK UP BY CONSIGNEE',
        call_required: true,
        photo_required: false,
        reason_required: false,
        two_step: false,
        customer_confirmation: false,
        max_photos: 0,
        photo_description: '',
    },
    23: {
        status_id: 23,
        name: 'PARTIAL DELIVERY',
        call_required: false,
        photo_required: false,
        reason_required: true,
        two_step: false,
        customer_confirmation: false,
        max_photos: 0,
        photo_description: '',
    },
    28: {
        status_id: 28,
        name: 'PICKED UP',
        call_required: false,
        photo_required: false,
        reason_required: false,
        two_step: false,
        customer_confirmation: true,
        max_photos: 5,
        photo_description: 'Take photos of picked up items',
    },
    30: {
        status_id: 30,
        name: 'RECEIVED AT OPERATIONS FACILITY',
        call_required: false,
        photo_required: false,
        reason_required: false,
        two_step: false,
        customer_confirmation: false,
        max_photos: 0,
        photo_description: '',
    },
    31: {
        status_id: 31,
        name: 'RESCHEDULED FOR DELIVERY',
        call_required: false,
        photo_required: false,
        reason_required: true,
        two_step: false,
        customer_confirmation: false,
        max_photos: 0,
        photo_description: '',
    },
    34: {
        status_id: 34,
        name: 'SHIPMENT BEING RETURNED',
        call_required: false,
        photo_required: false,
        reason_required: false,
        two_step: false,
        customer_confirmation: false,
        max_photos: 0,
        photo_description: '',
    },
    37: {
        status_id: 37,
        name: 'WAREHOUSE SCAN',
        call_required: false,
        photo_required: false,
        reason_required: false,
        two_step: false,
        customer_confirmation: false,
        max_photos: 0,
        photo_description: '',
    },
    38: {
        status_id: 38,
        name: 'SHIPMENT REFUSED',
        call_required: false,
        photo_required: false,
        reason_required: true,
        two_step: false,
        customer_confirmation: false,
        max_photos: 0,
        photo_description: '',
    },
    47: {
        status_id: 47,
        name: 'COD/CASH COLLECTED',
        call_required: false,
        photo_required: false,
        reason_required: false,
        two_step: true,
        customer_confirmation: false,
        max_photos: 1,
        photo_description: 'Take a photo of the online payment confirmation',
    },
    52: {
        status_id: 52,
        name: 'LEFT MESSAGE NOTE AT DOOR 2ND ATTEMPT',
        call_required: true,
        photo_required: true,
        reason_required: false,
        two_step: false,
        customer_confirmation: false,
        max_photos: 2,
        photo_description: 'Take a photo of the location',
    },
    59: {
        status_id: 59,
        name: 'WRONG CASES / PACKAGING',
        call_required: false,
        photo_required: true,
        reason_required: false,
        two_step: false,
        customer_confirmation: false,
        max_photos: 3,
        photo_description: 'Take a photo showing the damage or packaging problem clearly',
    },
    63: {
        status_id: 63,
        name: 'CONSIGNEE MOVED',
        call_required: false,
        photo_required: false,
        reason_required: false,
        two_step: false,
        customer_confirmation: false,
        max_photos: 0,
        photo_description: '',
    },
    64: {
        status_id: 64,
        name: 'BUSINESS CLOSED',
        call_required: false,
        photo_required: false,
        reason_required: false,
        two_step: false,
        customer_confirmation: false,
        max_photos: 0,
        photo_description: '',
    },
};

const DEFAULT_STATUS_PERMISSIONS: StatusPermissions = {
    permissions: {
        freight: [10, 16, 17, 22, 23, 28, 30, 31, 34, 37, 38, 47, 52, 59, 63, 64],
        pd: [10, 16, 17, 22, 23, 28, 31, 34, 37, 38, 47, 52, 59, 63, 64],
        subcontractor: [10, 16, 17, 22, 23, 28, 31, 34, 37, 38, 47, 52, 59, 63, 64],
    },
    warehouse_scan_statuses: [37],
    delivered_status_id: 10,
    version: '1.0.0',
    updated_at: '2025-02-16T00:00:00.000Z',
};

const DEFAULT_GEOFENCE: GeofenceConfig = {
    locations: [
        {
            id: 'warehouse_main',
            name: 'Miles Express Warehouse',
            latitude: 35.8751997,
            longitude: 14.4945183,
            radius_meters: 500,
            type: 'warehouse',
            is_active: true,
            applies_to_statuses: [37],
        },
    ],
    version: '1.0.0',
    updated_at: '2025-02-16T00:00:00.000Z',
};

const DEFAULT_VALIDATIONS: StatusValidations = {
    rules: [
        {
            status_id: 17,
            rule_type: 'blocks_if_exists',
            condition_status_id: 17,
            error_message: 'Left Message Note 1 has already been used for this parcel. You cannot use it again.',
            warning_message: 'Use Left Message Note 2 instead.',
            suggested_status_id: 52,
        },
        {
            status_id: 52,
            rule_type: 'requires_previous',
            condition_status_id: 17,
            error_message: 'You must use Left Message Note 1 before using Note 2.',
        },
        {
            status_id: 52,
            rule_type: 'blocks_if_exists',
            condition_status_id: 52,
            error_message: 'Left Message Note 2 has already been used for this parcel. You cannot use it again.',
            warning_message: 'Use "Shipment Refused" instead (only when agreed with PD).',
            suggested_status_id: 38,
        },
        {
            status_id: 17,
            rule_type: 'daily_limit',
            max_count: 3,
            error_message: 'You have exceeded the daily limit for Left Message Note 1.',
            warning_message: 'You have used this status multiple times today. Supervisor has been notified.',
        },
        {
            status_id: 52,
            rule_type: 'daily_limit',
            max_count: 3,
            error_message: 'You have exceeded the daily limit for Left Message Note 2.',
            warning_message: 'You have used this status multiple times today. Supervisor has been notified.',
        },
    ],
    left_message_statuses: [17, 52],
    version: '1.0.0',
    updated_at: '2025-02-16T00:00:00.000Z',
};

const DEFAULT_UI_CONTENT: UIContentConfig = {
    status_content: [
        {
            status_id: 10,
            instructions: [],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'checkmark-circle-outline',
            icon_color: '#10b981',
        },
        {
            status_id: 16,
            instructions: ['Take PHOTO of parcel'],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'call-outline',
            icon_color: '#3b82f6',
        },
        {
            status_id: 17,
            instructions: [
                'CALL the customer first!',
                'Confirm: "I called the customer"',
                'Take PHOTO of location + Note',
            ],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'document-text-outline',
            icon_color: '#f59e0b',
        },
        {
            status_id: 22,
            instructions: [
                'CALL the customer first!',
                'Confirm they will pick up',
                'Click confirmation: "I confirmed that I called the customer"',
            ],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'pause-circle-outline',
            icon_color: '#8b5cf6',
        },
        {
            status_id: 23,
            instructions: ['Write HOW MANY pieces are missing (mandatory)'],
            reason_placeholder: 'e.g., 2 pieces missing, 1 box missing',
            reason_examples: ['2 pieces missing', '1 box missing', '3 items not delivered'],
            icon_name: 'pie-chart-outline',
            icon_color: '#f97316',
        },
        {
            status_id: 28,
            instructions: [],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'hand-left-outline',
            icon_color: '#10b981',
        },
        {
            status_id: 30,
            instructions: [],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'home-outline',
            icon_color: '#6b7280',
        },
        {
            status_id: 31,
            instructions: ['Write the REASON (mandatory)'],
            reason_placeholder: 'e.g., Customer wants delivery on Monday, Office closed try tomorrow',
            reason_examples: [
                'Customer wants delivery on Monday',
                'Office closed, try tomorrow',
                'Customer on holiday until Friday',
            ],
            icon_name: 'calendar-outline',
            icon_color: '#f59e0b',
        },
        {
            status_id: 34,
            instructions: [],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'return-up-back-outline',
            icon_color: '#ef4444',
        },
        {
            status_id: 37,
            instructions: [],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'business-outline',
            icon_color: '#6b7280',
        },
        {
            status_id: 38,
            instructions: ['Write the REASON (mandatory)'],
            reason_placeholder: 'e.g., Customer changed mind, Customer did not order this, Customer cannot pay COD',
            reason_examples: [
                'Customer changed mind',
                'Customer did not order this',
                'Customer cannot pay COD',
            ],
            icon_name: 'ban-outline',
            icon_color: '#ef4444',
        },
        {
            status_id: 47,
            instructions: [
                'Select "COD/Cash Collected"',
                'Confirm the amount you collected / Or Write if different',
                'Then scan again → "Delivered"',
            ],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'cash-outline',
            icon_color: '#10b981',
        },
        {
            status_id: 52,
            instructions: [
                'CALL the customer first!',
                'Confirm: "I called the customer"',
                'Take PHOTO of location',
            ],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'document-text-outline',
            icon_color: '#f59e0b',
        },
        {
            status_id: 59,
            instructions: ['Take PHOTO of the parcel', 'Show the damage or problem clearly!'],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'warning-outline',
            icon_color: '#ef4444',
        },
        {
            status_id: 63,
            instructions: [],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'arrow-forward-outline',
            icon_color: '#6b7280',
        },
        {
            status_id: 64,
            instructions: [],
            reason_placeholder: '',
            reason_examples: [],
            icon_name: 'lock-closed-outline',
            icon_color: '#6b7280',
        },
    ],
    labels: {
        call_confirmation_title: 'Call Required',
        call_confirmation_message: 'Before using this status, you MUST call the customer first!',
        call_confirmation_question: 'Did you call the customer?',
        call_confirmation_yes: 'Yes, I Called',
        call_confirmation_no: 'No, Cancel',
        photo_required_title: 'Photo Required',
        reason_mandatory_text: 'Reason is MANDATORY',
        cod_reminder: 'After confirming COD, scan the parcel again and select "Delivered"',
        monitoring_note: 'This confirmation is being monitored',
    },
    version: '1.0.0',
    updated_at: '2025-02-16T00:00:00.000Z',
};

export const DEFAULT_CONFIG = {
    statusRules: DEFAULT_STATUS_RULES,
    statusPermissions: DEFAULT_STATUS_PERMISSIONS,
    geofence: DEFAULT_GEOFENCE,
    validations: DEFAULT_VALIDATIONS,
    uiContent: DEFAULT_UI_CONTENT,
    version: '1.0.0',
};